# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('display_in_menu', models.BooleanField(default=False, verbose_name='Display in top bar')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['title'],
            },
        ),
    ]
