# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:37
from __future__ import unicode_literals

import adverts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('active_from', models.DateTimeField(verbose_name='Active from')),
                ('active_until', models.DateTimeField(verbose_name='Active until')),
                ('image_desktop', sorl.thumbnail.fields.ImageField(blank=True, upload_to=adverts.models.get_banner_filename, verbose_name='Image – desktop')),
                ('image_mobile', sorl.thumbnail.fields.ImageField(blank=True, upload_to=adverts.models.get_banner_filename, verbose_name='Image – mobile')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('link', models.CharField(blank=True, max_length=600, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Link')),
                ('text', models.TextField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Text')),
                ('display_on_frontpage', models.BooleanField(default=False, verbose_name='Display on front page')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, upload_to='partners', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('slug', models.SlugField(max_length=120, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Advertisement position',
                'verbose_name_plural': 'Advertisement positions',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.Advertiser', verbose_name='Advertiser'),
        ),
        migrations.AddField(
            model_name='advert',
            name='position',
            field=models.ManyToManyField(to='adverts.Position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='advert',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Tags'),
        ),
    ]
