# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=320, verbose_name='Text')),
                ('link', models.CharField(max_length=256, verbose_name='Link')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='animals/', verbose_name='Animal photo')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.CharField(choices=[('dog', 'Dogs'), ('cat', 'Cats')], max_length=8, verbose_name='Category')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Shelter animal',
                'verbose_name_plural': 'Shelter animals',
                'ordering': ['-time_created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together=set([('id', 'category')]),
        ),
    ]
