# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import krimiplzen.mixins
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^(?:(?!FOTO|FOTKY|VIDEO|AKTU).)*$')], verbose_name='Title')),
                ('intro', models.CharField(blank=True, max_length=720, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Introduction')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('author_name', models.CharField(blank=True, help_text='Displayed author name', max_length=60, null=True, verbose_name='Author name')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(choices=[('p', 'Published'), ('a', 'Accessible'), ('x', 'Inacessible')], default='p', help_text="<b>Published</b> – appears on website<br><b>Accessible</b> – does not appear on website, but can beopened with URL or link<br><b>Inaccessible</b> – can't be opened, links result in 'Page not found'", max_length=1, verbose_name='Status')),
                ('liveupdates', models.BooleanField(default=True, help_text='Automatically push article updates to visitors.', verbose_name='Live updates')),
                ('photo_cover', models.BooleanField(default=False, verbose_name='Photo cover')),
                ('photo_cover_light', models.BooleanField(default=False, verbose_name='Dark text on a light photo')),
                ('video_ad', models.BooleanField(default=True, verbose_name='Allow ad before video')),
                ('allow_ads', models.BooleanField(default=True, verbose_name='Show ads')),
                ('cover_photo', sorl.thumbnail.fields.ImageField(blank=True, upload_to='foto/covers/', verbose_name='Cover photo')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.Advertiser', verbose_name='Article partner')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='articles.Article', verbose_name='Related articles')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-time_created', 'title'],
                'get_latest_by': 'time_created',
            },
            bases=(krimiplzen.mixins.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('color', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color')),
                ('hide_after', models.IntegerField(blank=True, help_text='Number of hours from the latest article update whenthe sticker is visible.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hide after')),
                ('is_public', models.BooleanField(default=True, verbose_name='Display on website')),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='stickers',
            field=models.ManyToManyField(blank=True, to='articles.Sticker', verbose_name='Stickers'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Tags'),
        ),
    ]
