# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 00:57
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='foto/covers/', verbose_name='Cover photo'),
        ),
    ]
