# Generated by Django 2.0.4 on 2018-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180406_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_published',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Published at'),
        ),
    ]
