# Generated by Django 2.0.4 on 2018-04-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_time_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='liveupdates',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_cover_light',
        ),
        migrations.RemoveField(
            model_name='article',
            name='related_articles',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_ad',
        ),
    ]
