# Generated by Django 2.0.4 on 2018-04-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180418_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='allow_ads',
        ),
        migrations.RemoveField(
            model_name='article',
            name='liveupdates',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_cover_light',
        ),
        migrations.RemoveField(
            model_name='article',
            name='related_articles',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_ad',
        ),
        migrations.AddField(
            model_name='article',
            name='time_published',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Created at'),
        ),
    ]
